ingressController:
  enabled: false

env:
  database: "off"
  plugins: "bundled,custom-header"
  lua_package_path: "/opt/?.lua;;"

dblessConfig:
  config:
    _format_version: "3.0"
    # Include content from kong.yaml here directly, or mount via ConfigMap

plugins:
  configMaps:
    - name: kong-plugin-custom-header
      pluginName: custom-header